# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
{% if cookiecutter.project_packages == "All" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - polars
  - pandas
  - matplotlib
  - numpy
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
{% elif cookiecutter.project_packages == "Exploratory" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - polars
  - pandas
  - matplotlib
  - numpy
  - seaborn
  - scipy
  - statsmodels
  {% endif -%}
  - pip
#{% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
#{% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
  {% if cookiecutter.project_packages == "All" -%}
  - pyhere
  {% endif -%}